cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

checkout/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("add/order/<int:id>", views.add_order, name='add_order'),
    path("cart", views.cart, name='cart'),
]

karl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    # path('order', include('checkout.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('order_create', views.order_create, name='order_create'),
    path('checkout', views.checkout, name='checkout'),
]

cart/models.py
from django.db import models

# Create your models here.

checkout/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from order.forms import OrderCreateForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
        return render(request, 'cart/cart.html', {'cart': cart})
    else:
        return render(request, 'cart/cart.html')



# Create your views here.

checkout/views.py
from datetime import datetime, timedelta

from django.shortcuts import render, redirect
from django.http import HttpResponse
import json

from shop.models import Product


def cart(request):
    session_product = []
    products = []
    product_ids = []
    if "product" in request.session:
        session_product = request.session["product"]
    for item in session_product:
        product_ids.append(item['product_id'],)
    if session_product:
        products = Product.objects.filter(id__in=product_ids)
    return render(request, 'checkout1/cart.html', {'products': products})


def add_order(request, id):
    product_json = []
    if "product" in request.session:
        product_json = request.session["product"]
    product_json.append({'product_id': id, 'qty': 1})
    request.sessions['product'] = product_json
    request.sessions.modified = True
    return redirect('cart')

templates/cart/cart.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

        <!-- ****** Cart Area Start ****** -->
        <div class="cart_area section_padding_100 clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="cart-table clearfix">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                        {% with product=item.product  %}
                                            <tr>
                                                <td class="cart_product_img d-flex align-items-center">
                                                    <a href="{{ product.get_absolute_url }}"><img src="{% if product.image_1 %}{{ product.image_1.url }}{% else %}{%  static 'img/product-img/1.jpg' %} {% endif %}" alt="Product"></a>
                                                    <h6>{{ product.name }}</h6>
                                                </td>
                                                <td class="price"><span>$ {{ item.price }}</span></td>
                                                <td class="quantity"><span>{{ item.quantity }}</span></td>
                                                <td class="num">${{ item.total_price }}</td>
                                                 <td><a class="btn btn-danger" href="{% url 'cart:cart_remove' product.id %}"><i class="fa fa-trash"></i></a></td>
                                                <td><a class="btn btn-warning" data-toggle="modal" data-target="#sndModal{{ item.id }}"><i class="fa fa-pencil"></i></a></td>
                                                <div id="sndModal{{ item.id }}" class="modal fade" tabindex="-1">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title">Update modal</h5>
                                                                <button class="close" data-dismiss="modal">x</button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <form action="{%  url 'cart:cart_add' product.id %}" method="post">
                                                                    {% csrf_token %}
                                                                        <label class="form-label_1", style="font-weight: bold">Количество</label>
                                                                            {{ item.update_quantity_form.quantity }}
                                                                            {{ item.update_quantity_form.update }}
                                                                            <input type="submit" value="Update">
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </tr>
                                        {% endwith %}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="cart-footer d-flex mt-30">
                            <div class="back-to-shop w-50">
                                <a href="{% url 'product' %}">Continue shoping</a>
                                <a href="{% url "order:checkout" %}">Checkout</a>
                            </div>
                            <div class="update-checkout w-50 text-right">
                                <a style="margin-bottom: 100px"><span><strong>Total</strong></span> <span><strong>{{ cart.get_total_price }}</strong></span></a>
{#                                <a href="#">clear cart</a>#}
{#                                <a href="#">Update cart</a>#}
                            </div>
                        </div>
                    </div>
                </div>
{##}
{#                <div class="row">#}
{#                    <div class="col-12 col-lg-4">#}
{#                        <div class="cart-total-area mt-70">#}
{#                            <div class="cart-page-heading">#}
{#                                <h5>Cart total</h5>#}
{#                                <p>Final info</p>#}
{#                            </div>#}
{##}
{#                            <ul class="cart-total-chart">#}
{#                                <li><span>Subtotal</span> <span>$59.90</span></li>#}
{#                                <li><span>Shipping</span> <span>Free</span></li>#}
{#                                <li><span><strong>Total</strong></span> <span><strong>{{ cart.get_total_price }}</strong></span></li>#}
{#                            </ul>#}
{#                            <a href="{% url "order:checkout" %}" class="btn karl-checkout-btn">Proceed to checkout</a>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
        <!-- ****** Cart Area End ****** -->
{% endblock content %}

templates/cart/checkout.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

        <!-- ****** Checkout Area Start ****** -->
        <div class="checkout_area section_padding_100">
            <div class="container">
                <div class="row">

                    <div class="col-12 col-md-6">
                        <div class="checkout_details_area mt-50 clearfix">

                            <div class="cart-page-heading">
                                <h5>Your data</h5>
                                <p>Thanks for choosing</p>
                            </div>
                            <form action="{% url "order:order_create" %}" method="post" class="order-form">
                                {{ form.name }}<br>
                                {{ form.phone_number }}<br>
                                {{ form.email }}<br>
{#                                {{ form.as_p }}#}
                                <p><input type="submit" class="btn btn-pill btn-danger" value="Place order"></p>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>

                    <div class="col-12 col-md-6 col-lg-5 ml-lg-auto">
                        <div class="order-details-confirmation">

                            <div class="cart-page-heading">
                                <h5>Your Order</h5>
                                <p>The Details</p>
                            </div>

                            <ul class="order-details-form mb-4">
                                {% for item in cart %}
                                    <li>
                                        {{ item.quantity }}x {{ item.product.name }}
                                        <span>${{ item.total_price }}</span>
                                    </li>
{#                                    <li><span>Product</span> <span>Total</span></li>#}
{#                                    <li><span>{{ item.product.name }}</span> <span>$ {{ item.quantity }}</span></li>#}
{#                                    <li><span>Shipping</span> <span>Free</span></li>#}
{#                                    <li><span>Total</span> <span>$ {{ item.total_price }}</span></li>#}
                                {% endfor %}
                            </ul>
                            <p>Total: ${{ cart.get_total_price }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ****** Checkout Area End ****** -->
{% endblock content %}

templates/cart/successful.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <i class="fa fa-check-circle-o" style="margin-left: 620px;margin-top: 100px;color: #0D84DB;font-size: 100px"></i>
<h1 style="margin-bottom: 20px;margin-left: 550px">Thank you</h1>
    <p style="margin-left: 400px;margin-bottom: 150px">Your order has been successfully completed.
        Your order number is <strong>{{ order.id }}</strong>.</p>
{% endblock %}