cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

karl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    # path('order', include('checkout.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/foooter.html
<!-- ****** Footer Area Start ****** -->
{% load static %}
        <footer class="footer_area">
            <div class="container">
                <div class="row">
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="single_footer_area">
                            <div class="footer-logo">
                                <img src="{% static 'img/core-img/logo.png' %}" alt="">
                            </div>
                            <div class="copywrite_text d-flex align-items-center">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> &amp; distributed by <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                            </div>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
                        <div class="single_footer_area">
                            <ul class="footer_widget_menu">
                                <li><a href="#">About</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Faq</a></li>
                                <li><a href="#">Returns</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
                        <div class="single_footer_area">
                            <ul class="footer_widget_menu">
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">Shipping</a></li>
                                <li><a href="#">Our Policies</a></li>
                                <li><a href="#">Afiliates</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-lg-5">
                        <div class="single_footer_area">
                            <div class="footer_heading mb-30">
                                <h6>Subscribe to our newsletter</h6>
                            </div>
                            <div class="subscribtion_form">
                                <form action="#" method="post">
                                    <input type="email" name="mail" class="mail" placeholder="Your email here">
                                    <button type="submit" class="submit">Subscribe</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="line"></div>

                <!-- Footer Bottom Area Start -->
                <div class="footer_bottom_area">
                    <div class="row">
                        <div class="col-12">
                            <div class="footer_social_area text-center">
                                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- ****** Footer Area End ****** -->
    </div>
    <!-- /.wrapper end -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->

    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
           <!-- Latest compiled and minified JavaScript -->
     <script src="https://mazcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
             integrity="sha384-Tc5IQib027qyyjSMfHjOMaLkfuWVxZUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7txa"
             crossorigin="anonymous"></script>
     <script>
         $('#sndModal').modal("tooggle")
     </script>

</body>

</html>

templates/include/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Karl - Fashion Ecommerce Template | Home</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Responsive CSS -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <script src="https://cdn.lordicon.com/libs/mssddfmo/lord-icon-2.1.0.js"></script>

</head>

templates/include/sidebar.html
<body>
{% load static %}
<!--    <div class="catagories-side-menu">-->
<!--        &lt;!&ndash; Close Icon &ndash;&gt;-->
<!--        <div id="sideMenuClose">-->
<!--            <i class="ti-close"></i>-->
<!--        </div>-->
<!--        &lt;!&ndash;  Side Nav  &ndash;&gt;-->
<!--        <div class="nav-side-menu">-->
<!--            <div class="menu-list">-->
<!--                <h6>Categories</h6>-->
<!--                <ul id="menu-content" class="menu-content collapse out">-->
<!--                    &lt;!&ndash; Single Item &ndash;&gt;-->
<!--                    <li data-toggle="collapse" data-target="#women" class="collapsed active">-->
<!--                        <a href="#">Woman wear <span class="arrow"></span></a>-->
<!--                        <ul class="sub-menu collapse" id="women">-->
<!--                            <li><a href="#">Midi Dresses</a></li>-->
<!--                            <li><a href="#">Maxi Dresses</a></li>-->
<!--                            <li><a href="#">Prom Dresses</a></li>-->
<!--                            <li><a href="#">Little Black Dresses</a></li>-->
<!--                            <li><a href="#">Mini Dresses</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                    &lt;!&ndash; Single Item &ndash;&gt;-->
<!--                    <li data-toggle="collapse" data-target="#man" class="collapsed">-->
<!--                        <a href="#">Man Wear <span class="arrow"></span></a>-->
<!--                        <ul class="sub-menu collapse" id="man">-->
<!--                            <li><a href="#">Man Dresses</a></li>-->
<!--                            <li><a href="#">Man Black Dresses</a></li>-->
<!--                            <li><a href="#">Man Mini Dresses</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                    &lt;!&ndash; Single Item &ndash;&gt;-->
<!--                    <li data-toggle="collapse" data-target="#kids" class="collapsed">-->
<!--                        <a href="#">Children <span class="arrow"></span></a>-->
<!--                        <ul class="sub-menu collapse" id="kids">-->
<!--                            <li><a href="#">Children Dresses</a></li>-->
<!--                            <li><a href="#">Mini Dresses</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                    &lt;!&ndash; Single Item &ndash;&gt;-->
<!--                    <li data-toggle="collapse" data-target="#bags" class="collapsed">-->
<!--                        <a href="#">Bags &amp; Purses <span class="arrow"></span></a>-->
<!--                        <ul class="sub-menu collapse" id="bags">-->
<!--                            <li><a href="#">Bags</a></li>-->
<!--                            <li><a href="#">Purses</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                    &lt;!&ndash; Single Item &ndash;&gt;-->
<!--                    <li data-toggle="collapse" data-target="#eyewear" class="collapsed">-->
<!--                        <a href="#">Eyewear <span class="arrow"></span></a>-->
<!--                        <ul class="sub-menu collapse" id="eyewear">-->
<!--                            <li><a href="#">Eyewear Style 1</a></li>-->
<!--                            <li><a href="#">Eyewear Style 2</a></li>-->
<!--                            <li><a href="#">Eyewear Style 3</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                    &lt;!&ndash; Single Item &ndash;&gt;-->
<!--                    <li data-toggle="collapse" data-target="#footwear" class="collapsed">-->
<!--                        <a href="#">Footwear <span class="arrow"></span></a>-->
<!--                        <ul class="sub-menu collapse" id="footwear">-->
<!--                            <li><a href="#">Footwear 1</a></li>-->
<!--                            <li><a href="#">Footwear 2</a></li>-->
<!--                            <li><a href="#">Footwear 3</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <div id="wrapper">

        <!-- ****** Header Area Start ****** -->
        <header class="header_area">
            <!-- Top Header Area Start -->
            <div class="top_header_area">
                <div class="container h-100">
                    <div class="row h-100 align-items-center justify-content-end">

                        <div class="col-12 col-lg-7">
                            <div class="top_single_area d-flex align-items-center">
                                <!-- Logo Area -->
                                <div class="top_logo">
                                    <a href="{% url 'home' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                                </div>
                                <!-- Cart & Menu Area -->
                                <div class="header-cart-menu d-flex align-items-center ml-auto">
                                    <!-- Cart Area -->
                                    <div class="cart">
                                        {% with total_items=cart|length %}
                                        {% if cart|length > 0 %}
                                            <a href="{% url 'cart:cart_detail' %}" target="_blank"><span class="cart_quantity">{{ total_items }}</span><i class="ti-bag"></i>Your Bag  $ {{ cart.get_total_price }}</a>
                                        {% else %}
                                            <a href="{% url 'cart:cart_detail' %}" target="_blank"><span class="cart_quantity">0</span><i class="ti-bag"></i>Your Bag</a>
                                        {%  endif %}
                                        {% endwith %}
                                        <!-- Cart List Area Start -->
{#                                        <ul class="cart-list">#}
{#                                            <li>#}
{#                                                <a href="#" class="image"><img src="{% static 'img/product-img/product-10.jpg' %}" class="cart-thumb" alt=""></a>#}
{#                                                <div class="cart-item-desc">#}
{#                                                    <h6><a href="#">Women's Fashion</a></h6>#}
{#                                                    <p>1x - <span class="price">$10</span></p>#}
{#                                                </div>#}
{#                                                <span class="dropdown-product-remove"><i class="icon-cross"></i></span>#}
{#                                            </li>#}
{#                                            <li>#}
{#                                                <a href="#" class="image"><img src="{% static 'img/product-img/product-11.jpg' %}" class="cart-thumb" alt=""></a>#}
{#                                                <div class="cart-item-desc">#}
{#                                                    <h6><a href="#">Women's Fashion</a></h6>#}
{#                                                    <p>1x - <span class="price">$10</span></p>#}
{#                                                </div>#}
{#                                                <span class="dropdown-product-remove"><i class="icon-cross"></i></span>#}
{#                                            </li>#}
{#                                            <li class="total">#}
{#                                                <span class="pull-right">Total: $20.00</span>#}
{#                                                <a href="cart.html" class="btn btn-sm btn-cart">Cart</a>#}
{#                                                <a href="checkout-1.html" class="btn btn-sm btn-checkout">Checkout</a>#}
{#                                            </li>#}
{#                                        </ul>#}
                                    </div>
<!--                                    <div class="header-right-side-menu ml-15">-->
<!--                                        <a href="#" id="sideMenuBtn"><i class="ti-menu" aria-hidden="true"></i></a>-->
<!--                                    </div>-->
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <!-- Top Header Area End -->
            <div class="main_header_area">
                <div class="container h-100">
                    <div class="row h-100">
                        <div class="col-12 d-md-flex justify-content-between">
                            <!-- Header Social Area -->
                            <div class="header-social-area">
                                <a href="https://www.pinterest.com/"><span class="karl-level">Share</span> <i class="fa fa-pinterest" aria-hidden="true"></i></a>
                                <a href="https://www.facebook.com/"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="https://twitter.com/?lang=ru"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="https://ru.linkedin.com/"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                            </div>
                            <!-- Menu Area -->
                            <div class="main-menu-area">
                                <nav class="navbar navbar-expand-lg align-items-start">

                                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#karl-navbar" aria-controls="karl-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"><i class="ti-menu"></i></span></button>

                                    <div class="collapse navbar-collapse align-items-start collapse" id="karl-navbar">
                                        <ul class="navbar-nav animated" id="nav">
                                            <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                                            <li class="nav-item"><a class="nav-link" href="{% url 'product' %}">Shop</a></li>
                                            <li class="nav-item"><a class="nav-link" href="#">About</a></li>
                                            <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                            <!-- Help Line -->
                            <div class="help-line">
                                <a href="tel:+346573556778"><i class="ti-headphone-alt"></i> +34 657 3556 778</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- ****** Header Area End ****** -->

        <!-- ****** Top Discount Area Start ****** -->
        <section class="top-discount-area d-md-flex align-items-center">
            <!-- Single Discount Area -->
            <div class="single-discount-area">
                <h5>Free Shipping &amp; Returns</h5>
                <h6><a href="{% url 'product' %}">BUY NOW</a></h6>
            </div>
            <!-- Single Discount Area -->
            <div class="single-discount-area">
                <h5>20% Discount for all dresses</h5>
                <h6>USE CODE: Colorlib</h6>
            </div>
            <!-- Single Discount Area -->
            <div class="single-discount-area">
                <h5>20% Discount for students</h5>
                <h6>USE CODE: Colorlib</h6>
            </div>
        </section>